mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from usersystem import views

urlpatterns = [
    path('usersystem/', include('usersystem.urls', namespace='usersystem')),
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    
]

mysite/usersystem/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name='usersystem'

urlpatterns = [
    path('admin/', admin.site.urls),
   # path('', views.add_user, name='add_user'),
   # path('manage_user/', views.manage_user, name="manage_user"),
   # path('edit_user/<int:user_id>', views.edit_user, name="edit_user"),
    path('', views.index, name='index'),
    path('userlogin/', views.userlogin, name="userlogin"),
    path('adminlogin/', views.adminlogin, name="adminlogin"),
    path('register/', views.register, name="register"),
    path('register_user/', views.register_user, name="register_user"),
    path('all_users/', views.all_users, name="all_users"),
    path('delete_user/<int:myid>', views.delete_user, name="delete_user"),
    path('get_user/<int:myid>', views.get_user, name="get_user"),
    path('update_user/<int:myid>', views.update_user, name="update_user"),
    path('approve_user/<int:myid>', views.approve_user, name="approve_user"),
    path('login_user/', views.login_user, name="login_user"),
    path('login_admin/', views.login_admin, name="login_admin"),
    path('logout_user/', views.logout_user, name="logout_user"),
    path('logout_admin/', views.logout_admin, name="logout_admin"),
    
    
    

]  

mysite/usersystem/models.py
from django.db import models

class Clients(models.Model):
    user_id = models.AutoField
    firstname = models.CharField(max_length=25)
    lastname = models.CharField(max_length=25)
    cnic = models.CharField(max_length=50)
    dob = models.DateField()
    age = models.IntegerField(default=0)
    gender = models.CharField(max_length=25)
    password = models.CharField(max_length=25)
    status = models.IntegerField(default=0)


    def __str__(self):
        return self.firstname

mysite/usersystem/forms.py
from django import forms
from django.forms import ModelForm
from .models import Clients
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class UserForm(forms.ModelForm):

    class Meta():
        model = Clients
        fields = {'firstname', 'lastname', 'cnic', 'dob', 'age', 'gender', 'password'}

mysite/usersystem/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import Clients
from django.contrib import auth
from django.contrib.auth.models import User
'''
def add_user(request, template_name='user_signup.html'):
    form = UserForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('usersystem:manage_user')
    return render(request, template_name, {'form':form})


def manage_user(request, template_name='manage_user.html'):
    users = Clients.objects.all()
    data = {'user': users}
    #data[objects_list] = user_data
    return render(request, template_name, data)


def edit_user(request, pk, template_name='user_signup.html'):
    book = get_object_or_404(Clients, pk=pk)
    form = UserForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('usersystem:manage_user')


'''

def index(request):
    return render(request, 'index.html')


def adminlogin(request):
    return render(request, 'adminlogin.html')

def userlogin(request):
    return render(request, 'userlogin.html')


def register(request):

    #return render(request, 'user_signup.html')
    return render(request, 'register_user.html')


def register_user(request):
    if request.method == 'POST':  # data sent by user
        data = Clients()
        data.firstname = request.POST.get('firstname', 'off')
        data.lastname=request.POST.get('lastname', 'off')
        data.cnic=request.POST.get('cnic', 'off')
        data.dob=request.POST.get('dob', 'off')
        data.age=request.POST.get('age', 'off')
        data.gender=request.POST.get('gender', 'off')
        data.password=request.POST.get('password', 'off')
        
        data.save()
        return redirect('usersystem:all_users')
    else:  # display empty form
        return render(request, 'register_user.html')
    

def all_users(request):
    users = Clients.objects.all()
    data = {'user': users}
    #data[objects_list] = user_data
    return render(request, 'all_users.html', data)


def delete_user(request, myid):

    instance = Clients.objects.get(id=myid)
    instance.delete()
    
    return redirect('usersystem:all_users')


def get_user(request, myid):

    user = Clients.objects.get(id=myid)
    data = {'user': user}
    return render(request, 'update_user.html', data)


def update_user(request, myid):

    if request.method == 'POST':  # data sent by user
        Clients.objects.filter(id=myid).update(firstname=request.POST.get('firstname', 'off'))
        Clients.objects.filter(id=myid).update(lastname=request.POST.get('lastname', 'off'))
        Clients.objects.filter(id=myid).update(cnic=request.POST.get('cnic', 'off'))
        #Clients.objects.filter(id=myid).update(dob=request.POST.get('dob', 'off'))
        Clients.objects.filter(id=myid).update(age=request.POST.get('age', 'off'))
        Clients.objects.filter(id=myid).update(gender=request.POST.get('gender', 'off'))
        Clients.objects.filter(id=myid).update(password=request.POST.get('password', 'off'))

        return redirect('usersystem:index')
    else:  # display empty form
        return HttpResponse("failed to update")


def approve_user(request, myid):

    Clients.objects.filter(id=myid).update(status=1)

    return redirect('usersystem:all_users')


def login_user(request):

    user = Clients.objects.filter(cnic=request.POST.get('login', 'off'), password=request.POST.get('password', 'off'), status=1)
    data = {'user':user}
    if user:
        return render(request, 'user_home.html', data)
    else:
        return HttpResponse('problem')


def login_admin(request):
    #password=request.POST.get('password', 'off')
    #username=request.POST.get('username', 'off')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user:
            return redirect('usersystem:all_users')
        else:
            return HttpResponse('problem')
    

def logout_user(request):
    
    return redirect('usersystem:index')


def logout_admin(request):
    
    return redirect('usersystem:index')

mysite/usersystem/templates/adminlogin.html
<div class="wrapper fadeInDown">
    <div id="formContent">
    
      <!-- Login Form -->
      <form class="form-horizontal" action="{% url 'usersystem:login_admin' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <input type="text" id="login" class="fadeIn second" name="username" placeholder="login">
        <input type="password" id="password" class="fadeIn third" name="password" placeholder="password">
        <button type="submit" class="fadeIn fourth" >Log On</button>      
      </form>
    </div>
  </div> 

mysite/usersystem/templates/all_users.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">

<div class="container">
    <div class="row">
        <section class="col-md-12">
            <h1 class="page-header">Users Management</h1>

            <div class="row text-center">
                <div class="=col-md-12">
                    <a class="btn btn-primary" href="{% url 'usersystem:register' %}">Register New User</a>
                    <a class="btn btn-primary" href="{% url 'usersystem:logout_admin' %}">Log Out</a>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="content">
                            <thead>
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">First Name</th>
                                    <th class="text-center">Last Name</th>
                                    <th class="text-center">CNIC</th>
                                    <th class="text-center">Date of Birth</th>
                                    <th class="text-center">Age</th>
                                    <th class="text-center">Gender</th>
                                    <th class="text-center">Password</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center" colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                     {% for i in user %}
                                <tr>
                                    <td class="text-center"> {{i.id}} </td>
                                    <td class="text-center"> {{i.firstname}} </td>
                                    <td class="text-center"> {{i.lastname}} </td>
                                    <td class="text-center"> {{i.cnic}} </td>
                                    <td class="text-center"> {{i.dob}} </td>
                                    <td class="text-center"> {{i.age}} </td>
                                    <td class="text-center"> {{i.gender}} </td>
                                    <td class="text-center"> {{i.password}} </td>
                                    {% if i.status == 0 %}
                                        <td class="text-center"><a href="{% url 'usersystem:approve_user' i.id %}"><button class="btn btn-danger">Not Approved</button></a></td>
                                    {% else  %}
                                        <td class="text-center"><a href="#"><button class="btn btn-success">Approved</button></a></td>
                                    {% endif %}
                                    
                                    <td class="text-center"><a href="{% url 'usersystem:delete_user' i.id %}"><span class="glyphicon glyphicon-trash"></span></a></td>
                                </tr>
                            {% endfor %}  
                            </tbody>
                        </table>

                    </div>

                </div>

            </div>
        </section>

    </div>

</div>

mysite/usersystem/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Django People</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

mysite/usersystem/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>Home</title>
</head>

<body>
<h1>Welcome to User Management System</h1>
<a href="{% url 'usersystem:userlogin' %}"><button class="btn btn-primary cart">User Login</button></a>
<a href="{% url 'usersystem:adminlogin' %}"><button class="btn btn-primary cart">Admin Login</button></a>
<a href="{% url 'usersystem:register' %}"><button class="btn btn-primary cart">Register New User?</button></a>

</body>
</html>

mysite/usersystem/templates/manage_user.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">

<div class="container">
    <div class="row">
        <section class="col-md-12">
            <h1 class="page-header">User Management</h1>

            <div class="row text-center">
                <div class="=col-md-12">
                    <a class="btn btn-primary" href="{% url 'usersystem:add_user' %}">Add User</a>
                </div>
            </div>
            <hr>

            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="content">
                            <thead>
                                <tr>
                                    
                                    <th>First Name</th>
                                    <th>Last Name</th>
                                    <th>CNIC</th>
                                    <th>Date of Birth</th>
                                    <th>Age</th>
                                    <th>Gender</th>
                                    <th>Password</th>
                                    <th class="text-center" colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                     {% for book in user %}
                                <tr>
                                    
                                    <td> {{book.firstname}} </td>
                                    <td> {{book.lastname}} </td>
                                    <td> {{book.cnic}} </td>
                                    <td> {{book.dob}} </td>
                                    <td> {{book.age}} </td>
                                    <td> {{book.gender}} </td>
                                    <td> {{book.password}} </td>

                                    <td class="text-center"><a href="{% url 'usersystem:edit_user/' %}">Edit User</a></td>
                                    <td class="text-center"><a href="" title="Delete User"><span class="glyphicon glyphicon-trash"></span></a></td>
                                </tr>
                            {% endfor %}  
                            </tbody>
                        </table>

                    </div>

                </div>

            </div>
        </section>

    </div>

</div>

mysite/usersystem/templates/register_user.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>

<div class="container">
    <h2 style="text-align:center">Register New User</h2><br>
</div>

<div class="container">
            <form class="form-horizontal" action="{% url 'usersystem:register_user' %}" name="UserForm" method="POST" enctype="multipart/form-data"> {% csrf_token %} 
                <div class="form-group">
                    <label for="firstname" class="col-sm-3 control-label">First Name*</label>
                    <div class="col-sm-6">
                        <input type="text" name="firstname" required placeholder="First Name" class="form-control" autofocus>
                    </div>
                </div>
                <div class="form-group">
                    <label for="lastname" class="col-sm-3 control-label">Last Name*</label>
                    <div class="col-sm-6">
                        <input type="text" name="lastname" required placeholder="Last Name" class="form-control">
                    </div>
                </div>
                
                
                <div class="form-group">
                    <label for="cnic" class="col-sm-3 control-label">CNIC (without Dashes)* </label>
                    <div class="col-sm-6">
                        <input type="tel" name="cnic" pattern="[0-9]{13}"  required placeholder="1234567890123" class="form-control">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="dob" class="col-sm-3 control-label">Date of Birth*</label>
                    <div class="col-sm-6">
                        <input type="date" name="dob" required class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="age" class="col-sm-3 control-label">Age* </label>
                    <div class="col-sm-6">
                        <input type="number" name="age" min="18" max="100" required placeholder="Age" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <label for="gender" class="col-sm-3 control-label">Gender* </label>
                    <div class="col-sm-6">
                        <select class="form-control form-control-lg" name="gender">
                            <option>Male</option>
                            <option>Female</option>
                          </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-3 control-label">Password*</label>
                    <div class="col-sm-6">
                        <input type="password" name="password" required id="password" placeholder="Password" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="confirmPassword" class="col-sm-3 control-label">Confirm Password*</label>
                    <div class="col-sm-6">
                        <input type="password" id="confirmpassword" required placeholder="Password" class="form-control">
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-3">
                        <span class="help-block">*Required fields</span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-3">
                        <button type="submit" class="btn btn-success btn-block">Register</button>
                        <button type="reset" class="btn btn-primary btn-block">Reset</button>
                    </div>
                </div>
                
            </form> 
        </div> 
    

mysite/usersystem/templates/update_user.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<div class="container">
    <h2 style="text-align:center">Update User Details</h2><br>
</div>
<div class="container">
    <form class="form-horizontal" action="{% url 'usersystem:update_user' user.id %}" method="POST" enctype="multipart/form-data"> {% csrf_token %} 
        
                
                <div class="form-group"> 
                    <label for="firstname" class="col-sm-3 control-label">First Name*</label>
                    <div class="col-sm-6">
                        <input type="text" name="firstname" required value="{{user.firstname}}" class="form-control" autofocus>
                    </div>
                </div>
                <div class="form-group">
                    <label for="lastname" class="col-sm-3 control-label">Last Name*</label>
                    <div class="col-sm-6">
                        <input type="text" name="lastname" required value="{{user.lastname}}" class="form-control">
                    </div>
                </div>
                
                
                <div class="form-group">
                    <label for="cnic" class="col-sm-3 control-label">CNIC* </label>
                    <div class="col-sm-6">
                        <input type="phoneNumber" name="cnic" pattern="[0-9]{13}" value="{{user.cnic}}" class="form-control">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="dob" class="col-sm-3 control-label">Date of Birth*</label>
                    <div class="col-sm-6">
                        <input type="date" name="date" required class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="age" class="col-sm-3 control-label">Age* </label>
                    <div class="col-sm-6">
                        <input type="number" name="age" min="18" max="100" required value="{{user.age}}" class="form-control">
                    </div>
                </div>
 
                <div class="form-group">
                    <label for="gender" class="col-sm-3 control-label">Gender* </label>
                    <div class="col-sm-6">
                        <select class="form-control form-control-lg" value="{{user.gender}}  name="gender">
                            <option>Male</option>
                            <option>Female</option>
                          </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-3 control-label">Password*</label>
                    <div class="col-sm-6">
                        <input type="password" name="password" id="password" required  class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="confirmPassword" class="col-sm-3 control-label">Confirm Password*</label>
                    <div class="col-sm-6">
                        <input type="password" id="confirmpassword"  class="form-control">
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-3">
                        <span class="help-block">*Required fields</span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-3">
                        <button type="submit" class="btn btn-success btn-block">Update</button>
                    </div>
                </div>



            </form> <!-- /form -->
        </div> <!-- ./container -->



<script>

    function setDate() {

        document.getElementById('dob').value = user.dob
    
    }

    setDate()
    </script>

mysite/usersystem/templates/user_home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Home-User</title>
     <style>
       
  </style>
  </head>
  
<body>
  {% for i in user %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usersystem:get_user' i.id %}">Update</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'usersystem:logout_user' %}">Log Out</a>
      </li>
 
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="button">Search</button>
    </form>
  </div>
</nav>
<h1>Welcome {{i.firstname}} </h1>
{% endfor %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    
  </body>
</html>

mysite/usersystem/templates/user_signup.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">

<div class="container">
    <div class="row">
        <section class="col-md-12">
            <h1 class="page-header">User Registration Form</h1>

            <div class="row text-center">

            </div>
            <hr>

            <div class="row">
                <div class="form-group">
                    <form class="form-horizontal"  method="POST" enctype="multipart/form-data"> {% csrf_token %}

                        <div class="form-group">
                            <table class="table table-responsive table-bordered">
                                {{form.as_table}}

                            </table>
 
                            <input type="submit" class="btn btn-primary" value="Register">

                        </div>

                    </form>

                </div>

            </div>
        </section>

    </div>

</div>

mysite/usersystem/templates/userlogin.html
<div class="wrapper fadeInDown">
  <div id="formContent">
  
    <!-- Login Form -->
    <form class="form-horizontal" action="{% url 'usersystem:login_user' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
      <input type="text" id="login" class="fadeIn second" name="login" required placeholder="login">
      <input type="password" id="password" class="fadeIn third" name="password" required placeholder="password">
      <button type="submit" class="fadeIn fourth" >Log On</button>
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a href="{% url 'usersystem:register'%}"><button>Register New User?</button></a>
    </div>

  </div>
</div>